Add field operators override
u12206050/directus-extension-filters-interface pull request #3
Opened 2024-05-07 12:58 UTC by benjamin-vauchel

# Description

By default, operators are determined based on the field type using the `getFilterOperatorsForType` function ( https://github.com/directus/directus/blob/78546678d0469012628a9ee71207ef4e9e608a27/packages/utils/shared/get-filter-operators-for-type.ts#L7)

For example, if the field type is  `string`, operators available in Directus interface will be : 
- `contains`
- `ncontains`
- `icontains`
- `starts_with`
- `nstarts_with`
- `istarts_with`
- `nistarts_with`
- `ends_with`
- `nends_with`
- `iends_with`
- `niends_with`
- `eq`
- `neq`
- `empty`
- `nempty`
- `null`
- `nnull`
- `in`
- `nin`

With the introduction of the new `operators` field property, it is now possible to specify a subset of operators for a given field. For example, you can set the operators to only include :
- `eq`
- `neq`

This feature is useful when the business logic handling the rule does not support all default operators.

# Changes Made

Added a new operators property to the `AdvProp` type.
Updated the logic to prioritize operators specified in the `operators` property over those determined by the `getFilterOperatorsForType` function.

# Screenshots

## Field edition
![image](https://github.com/u12206050/directus-extension-filters-interface/assets/781241/c7dc27e8-bf82-45d6-95d3-052eb21dea1f)

## Field interface
![image](https://github.com/u12206050/directus-extension-filters-interface/assets/781241/eb8bc06d-659d-4268-9741-ee0876e141fc)

# Testing

Manually tested on Directus 10.10.7

- [x] If field has no `operators` property, all operators available for this type are shown in interface 
- [x] If field has empty `operators` property, all operators available for this type are shown in interface 
- [x] If field has `operators` property, only those operators are shown in interface

2024-05-08 19:19 UTC, u12206050 requested changes
Thanks for the PR. Could you add the suggestions I made and then I'll take another look and approve it :)

2024-05-08 19:19 UTC, u12206050 commented on README.md
> +    operators: FieldFilterOperator[]
```suggestion
    operators?: FieldFilterOperator[]
```
Make it optional

2024-05-08 19:19 UTC, u12206050 commented on README.md
> +            "operators": [ // Override default operators for this type (@see @directus/utils/getFilterOperatorsForType)
```suggestion
             // (optional) Override default operators for this type (@see @directus/utils/getFilterOperatorsForType) 
            "operators": [
```

2024-05-08 19:19 UTC, u12206050 commented on src/components/nodes.vue
> +        const operators = (fieldInfo.operators && fieldInfo.operators.length > 0) ? fieldInfo.operators : getFilterOperatorsForType(fieldInfo.type || 'string');
```suggestion
        const operators = (Array.isArray(fieldInfo.operators) && fieldInfo.operators.length > 0) ? fieldInfo.operators : getFilterOperatorsForType(fieldInfo.type || 'string');
```

2024-05-09 05:53 UTC, u12206050 approved these changes

2024-05-09 05:53 UTC, merged

2024-05-13 07:10 UTC, benjamin-vauchel commented
Sorry, I was on holidays. Thanks for the suggestions and the merge.